name: aquahelper
description: Dein Helfer wenn es um die Wasserwerte deines Aquariums geht!
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.22.12+86


environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.3
  path: ^1.9.0
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  image: ^4.1.7
  image_cropper: ^8.0.0
  photo_manager: ^3.0.0
  intl: ^0.19.0
  uuid: ^4.4.0
  fl_chart: 0.69.2
  flutter_launcher_icons: ^0.14.0
  http: ^1.0.0
  awesome_notifications: ^0.10.0
  flutter_datetime_picker_plus: ^2.2.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.1
  csv: ^6.0.0
  permission_handler: ^11.3.1
  file_picker: ^8.1.4
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_database: ^11.2.0
  google_sign_in: ^6.2.2
  firebase_storage: ^12.3.7
  cached_network_image: ^3.4.1
  introduction_screen: ^3.1.14
  shared_preferences: ^2.3.3
  firebase_analytics: ^11.3.6
  firebase_crashlytics: ^4.2.0
  purchases_flutter: ^8.3.0
  purchases_ui_flutter: ^8.3.0
  table_calendar: ^3.1.2
  flutter_ringtone_player: ^4.0.0+3
  gal: ^2.3.0
  rate_my_app: ^2.2.0
  flutter_markdown: ^0.7.4+3
  google_mobile_ads: ^5.2.0
  provider: ^6.1.2
  sizer: ^3.0.0


dependency_overrides:
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  sqflite_common_ffi: ^2.3.0+4

flutter_icons:
  android: true  
  ios: true  
  image_path: "assets/aquahelper_icon.png"
  adaptive_icon_background: "assets/background.png"
  adaptive_icon_foreground: "assets/aquahelper_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/aquahelper_icon.png
    - assets/images/aquarium.jpg
    - assets/images/google.png
    - assets/soil.png
    - assets/quader.png
    - assets/buttons/fertilizer_calculator.png
    - assets/buttons/soil_calculator_activated.png
    - assets/buttons/soil_calculator_deactivated.png
    - assets/buttons/explorer.png
    - assets/buttons/ai_assistant.png
    - assets/buttons/light_calculator_activated.png
    - assets/buttons/light_calculator_deactivated.png
    - assets/buttons/stopwatch_deactivated.png
    - assets/buttons/stopwatch_activated.png
    - assets/buttons/osmosis_deactivated.png
    - assets/buttons/osmosis_activated.png
    - assets/images/runin_intro.png
    - assets/images/plant.png
    - assets/images/increase_ground.jpg
    - assets/images/island_ground.jpg
    - assets/images/increase.jpg
    - assets/images/island.jpg
    - assets/ai_assistant/ai_assistant.png
    - assets/buttons/runin_activated.png
    - assets/buttons/runin_deactivated.png
