name: aquahelper
description: Dein Helfer wenn es um die Wasserwerte deines Aquariums geht!
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  gallery_saver: ^2.3.2
  image: ^4.1.3
  image_cropper: ^4.0.1
  photo_manager: ^2.8.1
  intl: ^0.18.1
  uuid: ^4.2.1
  fl_chart: 0.65.0
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true  
  ios: true  
  image_path: "assets/aquahelper_icon.png"
  adaptive_icon_background: "assets/background.png"
  adaptive_icon_foreground: "assets/aquahelper_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/aquarium.jpg
