name: aquahelper
description: Dein Helfer wenn es um die Wasserwerte deines Aquariums geht!
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.13.3+56


environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.3
  path: ^1.9.0
  camera: ^0.11.0
  image_picker: ^1.1.0
  path_provider: ^2.1.3
  image: ^4.1.7
  image_cropper: ^6.0.0
  photo_manager: ^3.0.0
  intl: ^0.19.0
  uuid: ^4.4.0
  fl_chart: 0.68.0
  flutter_launcher_icons: ^0.13.1
  http: ^1.0.0
  awesome_notifications: ^0.9.3
  flutter_datetime_picker_plus: ^2.2.0
  url_launcher: ^6.2.6
  package_info_plus: ^8.0.0
  csv: ^6.0.0
  permission_handler: ^11.3.1
  file_picker: ^8.0.3
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  firebase_database: ^10.5.4
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.4
  cached_network_image: ^3.3.1
  introduction_screen: ^3.1.14
  shared_preferences: ^2.2.3
  firebase_analytics: ^10.10.4
  firebase_crashlytics: ^3.5.4
  purchases_flutter: ^6.28.0
  purchases_ui_flutter: ^6.28.0
  table_calendar: ^3.1.1


dependency_overrides:
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite_common_ffi: ^2.3.0+4

flutter_icons:
  android: true  
  ios: true  
  image_path: "assets/aquahelper_icon.png"
  adaptive_icon_background: "assets/background.png"
  adaptive_icon_foreground: "assets/aquahelper_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/aquahelper_icon.png
    - assets/images/aquarium.jpg
    - assets/images/google.png
    - assets/soil.png
    - assets/quader.png
    - assets/buttons/fertilizer_calculator.png
    - assets/buttons/soil_calculator.png
    - assets/buttons/explorer.png
    - assets/buttons/ai_assistant.png
    - assets/buttons/light_calculator.png
    - assets/buttons/stopwatch_deactivated.png
    - assets/buttons/stopwatch_activated.png
    - assets/buttons/osmosis_deactivated.png
    - assets/buttons/osmosis_activated.png
    - assets/images/plant.png