name: Integration

on:
  workflow_call:

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      - name: Download dependencies
        run: flutter pub get
      - name: Check linting
        run: flutter analyze
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      - name: Download dependencies
        run: flutter pub get
      - name: Check linting
        run: flutter test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      - name: Download dependencies
        run: flutter pub get
      - name: Build appbundle for Android
        run: flutter build appbundle
