name: Integration

on:
  workflow_call:

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      - name: Download dependencies
        run: flutter pub get
      - name: Check linting
        run: flutter analyze
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      - name: Download dependencies
        run: flutter pub get
      - name: Check linting
        run: flutter test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      - name: Download dependencies
        run: flutter pub get
      - name: Create key.properties
        run: |
            echo keyPassword=\${{ secrets.UPLOAD_KEYSTORE_PASSWORD }} > ${{env.PROPERTIES_PATH}}
            echo storePassword=\${{ secrets.UPLOAD_KEYSTORE_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
            echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
      - run: echo "${{ secrets.UPLOAD_KEYSTORE }}" | base64 --decode > android/app/upload_keystore.jks
      - name: Build APK for Android
        run: base64 -d <<< $KEY_JKS > ./android/app/upload_keystore.jks && flutter build apk
      - name: Upload job-artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk