name: Integration

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  integration:
    uses: ./.github/workflows/integration.yml
  deploy_to_firebase_testlab:
    uses: ./.github/workflows/test_deployment.yml

