name: Production Deployment (Google Play Store)
on:
  workflow_call:
env:
  PROPERTIES_PATH: "./android/key.properties"

jobs:
  deploy_to_google_play:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifact of integration-job
        uses: actions/download-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/
            # Creating the key.properties file

      - name: Create key.properties
        run: |
          echo keyPassword=\${{ secrets.UPLOAD_KEYSTORE_PASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.KEY_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
      - run: echo "${{ secrets.UPLOAD_KEYSTORE }}" | base64 --decode > android/app/upload_keystore.jks
      - name: Build AppBundle
        env:
          KEY_JKS: ${{ secrets.UPLOAD_KEYSTORE }}
          KEY_PASSWORD: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}
        run: base64 -d <<< $KEY_JKS > ./android/app/upload_keystore.jks && flutter build appbundle --release -v
      - name: Production deployment to Google Play Store
        uses: r0adkll/upload-google-play@v1.1.2
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_PLAYSTORE_JSON }}
          packageName: com.aquarium.aquahelper
          releaseFiles: build/app/outputs/flutter-appbundle/app-release.aab
          track: internal