name: Integration

on:
  push:
    branches: [ "*" ]

jobs:
  integration:
    uses: ./.github/workflows/integration.yml
    secrets: inherit
  deploy_to_google_play:
    needs: integration
    uses: ./.github/workflows/production_deployment.yml
    secrets: inherit