name: Integration & production-release on new release tag

on:
  release:
    types: [created, edited]

jobs:
  integration:
    uses: ./.github/workflows/integration.yml
    secrets: inherit
  deploy_to_firebase_for_test:
    needs: integration
    uses: ./.github/workflows/test_deployment.yml
    secrets: inherit
  deploy_to_google_play:
    needs: integration
    uses: ./.github/workflows/production_deployment.yml
    secrets: inherit