name: Test-Deployment (Firebase App Distribution)

on:
  workflow_call:


jobs:
  deploy_to_firebase_for_test:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact of integration-job
      - uses: actions/checkout@v2
          # APK-Artefakt herunterladen
          - uses: actions/download-artifact@v2
          with:
            name: app-release
      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          groups: tester
          file: build/app/outputs/flutter-apk/app-release.apk