name: Test-Deployment to Firebase Testlab

on:
  workflow_call:


jobs:
  deploy_to_firebase_testlab:
    runs-on: ubuntu-latest
    steps:
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ SERVICE_ACCOUNT_JSON }}
          packageName: com.aquarium.aquahelper
          releaseFiles: app/build/outputs/bundle/release/app-release.apk
          track: alpha
          status: inProgress