name: Test-Deployment to Firebase Testlab

on:
  workflow_call:


jobs:
  deploy_to_firebase_testlab:
    runs-on: ubuntu-latest
    steps:
      - name: Debug APK File
        run: ls -l app/build/outputs/apk/debug/

      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk