name: Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      - run: flutter --version
      - name: Check linting
        run: flutter analyze --no-fatal-infos --no-fatal-warnings
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      - run: flutter --version
      - name: Get dependencies
        run: flutter pub get
      - name: Start release build
        run: flutter build appbundle
